name: Déployer en prod
on:
push:
branches:
- main
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Deploy
uses: burnett01/rsync-deployments@5.2.1
with:
source: "."
destination: "user@serfveur.com:/var/www/html"
flags: "az"
exclude: ".git,node_modules"
delete: true
env:
SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
name: Déployer en prod
on:
push:
branches:
- main
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Deploy
uses: burnett01/rsync-deployments@5.2.1
with:
source: "."
destination: "user@serfveur.com:/var/www/html"
flags: "az"
exclude: ".git,node_modules"
delete: true
env:
SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}